import Header from "@/components/client/header"

import type { Metadata } from "next";
import { Lexend, Inter } from "next/font/google";
import "./globals.css";


const lexendFont = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendFont.variable} flex flex-col h-screen bold  antialiased text-shadow-sm `}
      >
        <Header />

        {children}

      </body>
    </html>
  );
}
